orange/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from home.views import ProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('registration.auth_urls')),
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r'^accounts/profile/', ProfileView.as_view(), name="profileView"),
    url(r'^project/', include('project.urls')),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url

from project.views import ProjectList, ProjectCreate, ProjectUpdate, ProjectDelete
from project.views import update_project, project_task_list, get_user_project_list, update_project_details, update_project_tasks, update_project_team



app_name='project'
urlpatterns = [
   url(r'^$', ProjectList.as_view(), name='projectList'),
   url(r'create/$', ProjectCreate.as_view(), name='projectCreate'),
   url(r'(?P<pk>[0-9]+)/$', ProjectUpdate.as_view(), name='projectUpdate'),
   url(r'(?P<pk>[0-9]+)/delete/$', ProjectDelete.as_view(), name='projectDelete'),
   url(r'^ajax/tasks/$', project_task_list, name='project_task_list'),
   url(r'^ajax/projects/$', get_user_project_list, name='get_user_project_list'),
   #url(r'^(?P<pk>[0-9]+)/', update_project, name='update_project'),
   url(r'^(?P<pk>[0-9]+)/details/', update_project_details, name='update_project_details'),
   url(r'^(?P<pk>[0-9]+)/tasks/', update_project_tasks, name='update_project_tasks'),
   url(r'^(?P<pk>[0-9]+)/team/', update_project_team, name='update_project_team'),
]

home/models.py
from django.db import models

# Create your models here.

project/models.py
import datetime

now = datetime.datetime.now()

from django.db import models
from django.utils import timezone
# Create your models here.
from django.conf import settings
from django.urls import reverse
from django.db import models

# Create your models here.
class Project(models.Model):
	name = models.CharField(max_length=120, verbose_name='Title')
	desc = models.CharField(max_length=300, verbose_name='Purpose')
	owners = models.ManyToManyField(settings.AUTH_USER_MODEL)
	start_date = models.DateField(verbose_name='Starts')
	end_date = models.DateField(verbose_name='Ends')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	objects = models.Manager() #the default manager
	
	class Meta:
		ordering = ('created',)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('project-detail', kwargs={'pk': self.pk})

	def days_until_go_live(self):
		until_go = self.end_date - datetime.date.today()
		return until_go.days
	

class ActiveTasks(models.Manager):
	def get_queryset(self):
		return super(ActiveTasks, self).get_queryset().filter(is_active=True)


class Task(models.Model):
	title = models.CharField(max_length=50, blank=False)
	project = models.ForeignKey(Project, on_delete=models.CASCADE)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	objects = models.Manager() #the default manager
	active = ActiveTasks() # the published objects manager

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('tasks-detail', kwargs={'pk': self.pk})


class ActiveProjectTeam(models.Manager):
	def get_queryset(self):
		return super(ActiveProjectTeam, self).get_queryset().filter(is_active=True)


class ProjectTeam(models.Model):
	project = models.ForeignKey(Project, on_delete=models.CASCADE) # relationship with the project
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # choose from the list of users invited to this project by the admins
	is_active = models.BooleanField(default=True) # prevents a user from logging anymore against the project 
	project_rate = models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Project rate') # what they are charged out for on the invoice
	percent_allocated = models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percent allocated to project') # how much time the individual is allocated to work on this project. 100% = FTE = 40 hours
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	objects = models.Manager() #the default manager
	active = ActiveProjectTeam() # the published objects manager
	
	class Meta:
		ordering = ('created',)

	def __str__(self):
		return str(self.id)

	def get_absolute_url(self):
		return reverse('project-team-detail', kwargs={'pk': self.pk})

home/forms.py
from django import forms
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.contrib.auth.models import User

UserModel = get_user_model()


class ProfileForm(forms.Form):

	class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions')
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

project/forms.py
from django.forms import ModelForm, DateTimeInput, Textarea, DateInput
from django.forms.models import inlineformset_factory
from project.models import Project, ProjectTeam, Task


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'desc', 'owners', 'start_date', 'end_date')
        widgets = {
        	'desc': Textarea(attrs={'cols': 40, 'rows': 4}),
             # need to create a validator that prevents a project start date occuring after the end date - if sd gte ed then error 
            'start_date': DateInput(format='%d %b %Y', attrs={'class': 'date-input'}),
            'end_date': DateInput(format='%d %b %Y', attrs={'class': 'date-input'}),
        }


class ProjectTeamForm(ModelForm):

    class Meta:
        model = ProjectTeam
        fields = '__all__'


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = '__all__'

TaskFormSet = inlineformset_factory(Project, Task, form=TaskForm, extra=0, can_delete=True, min_num=1)
ProjectTeamFormSet = inlineformset_factory(Project, ProjectTeam, form=ProjectTeamForm, extra=0, can_delete=True, min_num=1)

home/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import DetailView

# Create your views here.
class ProfileView(DetailView):
	template_name = "registration/profile.html"
	model = User

	def get_object(self, queryset=None):
		pk = self.request.user.username
		return User.objects.get(username=pk)

project/views.py
from __future__ import print_function
import json
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.db import IntegrityError, transaction
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.encoding import force_text
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseForbidden
from project.models import Project, Task, ProjectTeam
from project.forms import ProjectForm, TaskFormSet, ProjectTeamFormSet


# Create your views here.
class ProjectList(ListView):
    model = Project
    fields = ['name','desc','start_date','end_date']
	# def get_queryset(self):
	# 	user = self.request.user
	# 	users_project_list = ProjectTeam.objects.filter(user=user).values_list('project', flat=True)
	# 	return Project.objects.filter(id__in=users_project_list)


class ProjectCreate(CreateView):
    model = Project
    fields = ['name','desc','start_date','end_date']


class ProjectUpdate(UpdateView):
    model = Project
    form_class = ProjectForm

    def get_context_data(self, **kwargs):
        context = super(ProjectUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['task_formset'] = TaskFormSet(self.request.POST, instance=self.object, prefix="task")
            context['team_formset'] = ProjectTeamFormSet(self.request.POST, instance=self.object, prefix="team")
        else:
            context['task_formset'] = TaskFormSet(instance=self.object, prefix="task")
            context['team_formset'] = ProjectTeamFormSet(instance=self.object, prefix="team")
        return context 

    def form_valid(self, form):
        context = self.get_context_data()
        task_formset = context['task_formset']
        team_formset = context['team_formset']
        if team_formset.is_valid() and task_formset.is_valid():
            self.object = form.save()
            task_formset.instance = self.object
            task_formset.save()
            team_formset.instance = self.object
            team_formset.save()
            return redirect(self.success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('projectList')


# Create your views here.
# class ProjectList(ListView):
#     def get_queryset(self):
#         user = self.request.user
#         users_project_list = ProjectTeam.objects.filter(member=user).values_list('project', flat=True)
#         return Project.objects.filter(id__in=users_project_list)


@login_required
def update_project(request, **kwargs):
    """
    update draft project
    """
    # set variables
    pk = int(kwargs.get('pk'))
    current_project = get_object_or_404(Project, pk=pk)
    #create the formset, specifying the form you want to repeat and the baseformset that holds the validation rules
    if request.method == "POST":
        # populate the project form and the formset
        project_form = ProjectForm(request.POST, instance=current_project)
        team_formset = ProjectTeamFormSet(request.POST, instance=current_project, prefix="team")
        task_formset = TaskFormSet(request.POST, instance=current_project, prefix="task")
        # validate then save each form in the formset
        if project_form.is_valid() and team_formset.is_valid() and task_formset.is_valid():
            team_formset.save()
            task_formset.save()
            project_form.save()
            current_project.update_totals()
            messages.success(request, 'You have updated successfully updated your project.')
            return redirect(reverse('projects:projectList'))
        else:
            messages.error(request, 'An unexpected error occurred. Your project was NOT saved.')

    else:
        project_form = ProjectForm(instance=current_project)
        team_formset = ProjectTeamFormSet(instance=current_project, prefix="team")
        task_formset = TaskFormSet(instance=current_project, prefix="task")

    context = {
        'project' : current_project,
        'project_form' : project_form,
        'team_formset' : team_formset,
        'task_formset' : task_formset,
    }

    return render(request, 'project/project_update_form.html', context)


@login_required
class ProjectDisplay(DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super(ProjectDisplay, self).get_context_data(**kwargs)
        context['form'] = ProjectForm()
        return context


@login_required
def update_project_details(request, **kwargs):
    """
    update project details
    """
    # set variables
    pk = int(kwargs.get('pk'))
    current_project = get_object_or_404(Project, pk=pk)
    
    if request.method == "POST":
        # populate the project form
        project_form = ProjectForm(request.POST, instance=current_project)
        # validate then save form
        if project_form.is_valid():
            project_form.save()
            messages.success(request, 'Success! Your project details have been updated.')
            return redirect(reverse('projects:projectList'))
        else:
            messages.error(request, 'An unexpected error occurred. Project details NOT saved.')

    else:
        project_form = ProjectForm(instance=current_project)

    # add the requested project and form to the context
    context = {
        'project' : current_project,
        'project_form' : project_form,
    }

    return render(request, 'project/project_update_details.html', context)


@login_required
def update_project_tasks(request, **kwargs):
    """
    update project tasks
    """
    # set variables
    pk = int(kwargs.get('pk'))
    current_project = get_object_or_404(Project, pk=pk)
    if request.method == "POST":
        # create and populate formset
        task_formset = TaskFormSet(request.POST, instance=current_project, prefix="task")
        # validate then save each form in the formset
        if task_formset.is_valid():
            task_formset.save()
            messages.success(request, 'You have updated successfully updated your tasks.')
            return redirect(reverse('projects:projectList'))
        else:
            messages.error(request, 'An unexpected error occurred. Task information was NOT saved.')

    else:
        task_formset = TaskFormSet(instance=current_project, prefix="task")

    context = {
        'project' : current_project,
        'task_formset' : task_formset,
    }

    return render(request, 'project/project_update_tasks.html', context)


@login_required
def update_project_team(request, **kwargs):
    """
    update project team
    """
    # set variables
    pk = int(kwargs.get('pk'))
    current_project = get_object_or_404(Project, pk=pk)
    if request.method == "POST":
        # populate the formset
        team_formset = ProjectTeamFormSet(request.POST, instance=current_project, prefix="team")
        # validate then save each form in the formset
        if team_formset.is_valid():
            team_formset.save()
            messages.success(request, 'Success! Team information updated.')
            return redirect(reverse('projects:projectList'))
        else:
            messages.error(request, 'An unexpected error occurred. Your team information was NOT updated.')

    else:
        team_formset = ProjectTeamFormSet(instance=current_project, prefix="team")
        
    context = {
        'project' : current_project,
        'team_formset' : team_formset,
    }

    return render(request, 'project/project_update_team.html', context)


def project_task_list(request):
    project = request.GET.get('project', None)
    """data = {
        'project_tasks': 
    }"""
    project_task_list = dict(tasks = list(Task.active.filter(project=project).values('id', 'title')))
    return JsonResponse(project_task_list)

def get_user_project_list(request):
    #if request.user.is_authenticated:
    users_project_list = ProjectTeam.objects.filter(member=request.user).values_list('project')
    return JsonResponse(dict(projects = list(Project.active.filter(id__in=users_project_list).values('id', 'name'))))

home/templates/project/project_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block head_title %}Project Delete{% endblock %}
{% block content %}
<div class="container">
	<div class="row main">
		<div class="panel-heading">
			<div class="panel-title text-center">
				<h1 class="title">Project<span class="w3-text-deep-orange"> Delete</span></h1>
			</div>
		</div>
		<form action="" method="post">{% csrf_token %}
			<p>Are you sure you want to delete "{{ object }}"?</p>
			<input type="submit" value="Confirm" />
		</form>
	</div>
</div>

home/templates/project/project_form.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{# Load the tag library #}
{% load worka_tags %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}{{ project.name }}{% endblock %}


{% block extra_head %}
<script type="text/javascript">
    $(function() {
        $('#myTaskTable tbody tr').formset({
            prefix: '{{ task_formset.prefix }}',
            formCssClass: 'dynamic-taskformset'
        });
        $('#myTeamTable tbody tr').formset({
            prefix: '{{ team_formset.prefix }}',
            formCssClass: 'dynamic-teamformset'
        });
    })
    </script>
<script> $('#add_more').click(function() { cloneMore('div.table:last', 'myTaskTable'); }); </script>
      
{% endblock %}

{% block content %}
<br>
<br>
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<button class="btn btn-link"><a href="{% url 'project:projectList' %}"><i class="fa fa-arrow-left"></i> back to project list</a></button><br><br>
<ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#home">{{ project.name }}</a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#menu1">Tasks</a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#menu2">Team members</a></li>
  </ul>

<br/>
<div class="tab-content">
	<div id="home" class="tab-pane active">
		<div class="col col-6 card">
			<form class="form-horizontal" method="post" action="{% url 'project:projectUpdate' project.id %}">
				{% csrf_token %}
				{% bootstrap_form form %}<br>
				<div class="row text-right">  
					
					<button type="submit" class="btn btn-primary"><i class="fa fa-save fa-1"></i> Submit</button>
			</div><br>
			</form>
		</div>
	</div>
	<div id="menu1" class="tab-pane">
		<div class="col col-6 card">
			<form class="form-horizontal" id="myProjectTasks" action="." method="post">
				{% csrf_token %} 
				{{ task_formset.management_form }}
				<table id="myTaskTable" class="table table-hover">
					<thead><th>-</th>
						<th>Name</th>
						<th>Active</th>
						
					</thead>
					<tbody>
						{% for form in task_formset %}
						<tr><td>
							{% for fld in form.hidden_fields %}{{ fld }}{% endfor %}
							{% if form.instance.pk %}{{ form.DELETE }}{% endif %}
						
					</td>
					<td>{{form.title|addcss:"form-control"}}</td>
					<td>{{form.is_active|addcss:"form-control"}}</td>
					</tr>
						{% endfor %}
					</tbody>
				</table>
				<div class="row text-right">
					<button class="btn btn-warning btn-lg" id='add_more'><i class="fa fa-plus-circle"></i> Add new task</button>
					<button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-save fa-1"></i> Submit</button>
				</div>
			</form>
		</div>
	</div>
	<div id="menu2" class="tab-pane">
		<div class="col col-6 card">
		
		<form class="form-horizontal" id="myProjectTeam" action="." method="post">
			{% csrf_token %} 
			{{ team_formset.management_form }}
			<table id="myTeamTable"  class="table table-hover">
				<thead>
					<th>User</th>
					<th>Allocation %</th>
					<th>Active</th>
					<th>Rate $</th>
					<th>-</th>
				</thead>
				<tbody>
					{% for form in team_formset %}
						<tr>
							<td>
								{% for fld in form.hidden_fields %}{{ fld }}{% endfor %}
								{% if form.instance.pk %}{{ form.DELETE }}{% endif %}
								{{form.user|addcss:"form-control"}}
							</td>
							<td>{{form.percent_allocated|addcss:"form-control"}}</td>
							<td>{{form.is_active|addcss:"form-control"}}</td>
							<td>{{form.project_rate|addcss:"form-control"}}</td>
							<td></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<div class="row text-right">  
				<button><a href="{% url 'project:projectList' %}">project list <i class="fa fa-level-up fa-1"></i> </a></button>
				<button><i class="fa fa-plus-circle"></i> Add new row</button>
				<button type="submit"><i class="fa fa-save fa-1"></i> save</button>
			</div>
			<br>
		</form>
		</div>
		</div>
	</div>
</div>

<script>
	$(function () {
		$('.datetime-input').datetimepicker({
			format:'DD-MM-YYYY'
		});
	});
</script>

{% endblock %}

home/templates/project/project_list.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}{% trans "Project List" %}{% endblock %}

{% block content %}
<br>
<br>
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<div class="container">

  <h2>Project List</h2>
            <hr>
<a href="{% url 'project:projectCreate' %}"><h5 class="text-primary"><i class="fa fa-plus-circle"></i> add a new project</h5></a>
            <table class='table table-bordered table-hover'>
			<thead>
				<tr>
					<th>Title</th>
					<th>Description</th>
					<th>Start</th>
					<th>End</th>
					<th class="text-warning">Days2goLive</th>
				</tr>
				
			</thead>
			{% for project in project_list %}
			<tr>
				<td><a href="{% url 'project:projectUpdate' project.id %}">{{ project.name }}</a></td>
				<td>{{ project.desc }}</td>
				<td>{{ project.start_date|date:"d M y" }}</td>
				<td>{{ project.end_date|date:"d M y" }}</td>
				<td>{{ project.days_until_go_live }} days</td>
			</tr>
			{% endfor %}
		</table>
</div>


{% endblock %}

home/templates/project/project_update_details.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load worka_tags %}

{% block head_title %}projects{% endblock %}

{% block body_class %}detail{% endblock %}

{% block body_base %} 

{% if perms.projects.can_change_project %}

<div class="container">
    <div class="row"> 
        <ul class="nav nav-tabs">
            <li class="active"><a href="#">Edit project details</a></li>
            <li><a href="{% url 'projects:update_project_tasks' project.id %}">Manage project tasks</a></li>
            <li><a href="{% url 'projects:update_project_team' project.id %}">Manage the team</a></li>
        </ul>
    </div>
</div>

{% include "_messages.html" %}

<div class="container">
    <div class="row">
        <div class="page-header">
            <h3 class="text-primary">Edit project details...</h3>
        </div>
    </div>
       
    <div class="row">
        <form class="form-horizontal" id="myProjectDetails" action="." method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="row text-right">  
            <button class="btn btn-link btn-lg"><a href="{% url 'projects:projectList' %}">project list <i class="fa fa-level-up fa-1"></i> </a></button>
            <button class="btn btn-warning btn-lg"><i class="fa fa-plus-circle fa-1"></i> new</button>
            <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-save fa-1"></i> save</button>
        </div>
        </form>
        
    </div>
</div>	

{% else %}
    <div class="container"><p class="lead text-warning">You do not have the correct permissions to view this page.</p></div>
{% endif %}

<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'DD-MM-YYYY'
        });
    });
</script>

{% endblock %}

home/templates/project/project_update_form.html
{% extends "base.html" %}

{% load i18n %}
{% load account_tags %}
{% load static %}
{% load bootstrap3 %}
{% load worka_tags %}
{% block head_title %}projects{% endblock %}

{% block extra_head %}
<script type="text/javascript">
    $(function() {
        $('#myTaskTable tbody tr').formset({
            prefix: '{{ task_formset.prefix }}',
            formCssClass: 'dynamic-taskformset'
        });
        $('#myTeamTable tbody tr').formset({
            prefix: '{{ team_formset.prefix }}',
            formCssClass: 'dynamic-teamformset'
        });
    })
</script>
{% endblock %}

{% block body_class %}detail{% endblock %}

{% block body_base %} 
{% if perms.projects.can_change_project %}

{% include "_messages.html" %}
{% blocktrans %} {% endblocktrans %}
<div class="container">
    <div class="col col-md-8">
    <div class="row">
    <form class="form-horizontal" id="myProjectDetails" action="." method="post">
        <div class="page-header">
            <h3 class="text-primary">Edit project details...</h3>
        </div>{% include "projects/project_nav.html" %}
        {% csrf_token %} 
        {{ team_formset.management_form }}
        {{ task_formset.management_form }}
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#details-tab"><h4 class="text-primary"><i class="fa fa-info-circle fa-1"></i> Details</h4></a></li>
            <li><a data-toggle="tab" href="#team-tab"><h4 class="text-primary"><i class="fa fa-users"></i> Team members <span class="badge badge-pill badge-primary">{{ project.num_of_team_members }}</span></h4></a></li>
            <li><a data-toggle="tab" href="#tasks-tab"><h4 class="text-primary"><i class="fa fa-wrench"></i> Tasks <span class="badge badge-pill badge-primary">{{ project.num_of_tasks }}</span></h4></a></li>
        </ul>
        <div class="tab-content">
            <div id="details-tab" class="tab-pane fade in active">
                <div class="row">
                    <br>
                    {{ project_form|bootstrap_horizontal }}
                </div>
            </div>
            <div id="team-tab" class="tab-pane fade">
                <div class="row">
                    <table id="myTeamTable"  class="table table-striped table-hover">
                        <thead>
                            <th>User</th>
                            <th>Allocation %</th>
                            <th>Active</th>
                            <th>-</th>
                        </thead>
                         <tbody>
                            {% for form in team_formset %}
                                <tr><td>{% for fld in form.hidden_fields %}{{ fld }}{% endfor %}
                                        {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                                        {{form.member|addcss:"form-control"}}
                                    </td>
                                    <td>
                                        {{form.percent_allocated|addcss:"form-control"}}
                                    </td>
                                    <td>{{form.is_active|addcss:"form-control"}}</td>
                                    <td></td>
                                </tr>       
                            {% endfor %}
                        </tbody>
                    </table>
                    
                </div>
            </div>
            <div id="tasks-tab" class="tab-pane fade">
                <div class="row">
                    <table id="myTaskTable" class="table table-striped table-hover">
                        <thead>
                        	<th>Name</th>
                        	<th>Active</th>
                            <th>Start</th>
                            <th>Finish</th>
                            <th>-</th>
                        </thead>
                        <tbody>
                            {% for form in task_formset %}
                                <tr><td>
                                    {% for fld in form.hidden_fields %}{{ fld }}{% endfor %}
                                    {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                                    {{form.title|addcss:"form-control"}}
                                </td>
                                <td>{{form.is_active|addcss:"form-control"}}</td>
                                <td>{{form.start|addcss:"form-control"}}</td>
                                <td>{{form.finish|addcss:"form-control"}}</td>
                                <td></td></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
<hr></hr>
        <div class="row text-right">  
    		<button class="btn btn-link btn-lg"><a href="{% url 'projects:projectList' %}">project list <i class="fa fa-level-up fa-1"></i> </a></button>
            <button class="btn btn-warning btn-lg"><i class="fa fa-plus-circle fa-1"></i> new</button>
            <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-save fa-1"></i> save</button>
        </div>
    </form>
</div>	
</div></div>	

{% else %}
    <div class="container"><p class="lead text-warning">You do not have the correct permissions to view this page.</p></div>
{% endif %}

<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD'
        });
    });
</script>

{% endblock %}